### ISSUE TITLE
Recommend two papers about semantic segmentation

### ISSUE THREAD

**Issue by lartpang** [dkozlov/awesome-knowledge-distillation#11]
Knowledge Adaptation for Efficient Semantic Segmentation
https://arxiv.org/abs/1903.04688

Structured Knowledge Distillation for Semantic Segmentation
https://arxiv.org/abs/1903.04197

**Comment by dkozlov** [comment]
Hello @lartpang,
Could you please make a pull request with above papers?

**Comment by lartpang** [comment]
OK, I'm glad to do it.
