### ISSUE TITLE
Adding relevant paper

### ISSUE THREAD

**Issue by HFooladi** [dkozlov/awesome-knowledge-distillation#17]
Thanks for creating this repository and gathering lots of useful papers and materials. I think you can add the following paper to this list:

- Improved Knowledge Distillation via Teacher Assistant: Bridging the Gap Between Student and Teacher. [link to the paper](https://arxiv.org/abs/1902.03393)

Also, there is a good [implementation](https://github.com/imirzadeh/Teacher-Assistant-Knowledge-Distillation) of this paper in PyTorch.

**Comment by dkozlov** [comment]
Hello @HFooladi,

Could you please make a pull request with the above papers and implementation?
