### ISSUE TITLE
Quality about the listed papers

### ISSUE THREAD

**Issue by xiabingquan** [dkozlov/awesome-knowledge-distillation#35]
Some papers are far away from "awesome". For example, the paper \<\<Model Distillation with Knowledge Transfer from Face Classification to Alignment and Verification\>\> was rejected by ICLR2018. Maybe the paper is still unpublished.
I hope that the owner of this repo could be more strict with the quality of the listed papers, and append more information about the publication status of the papers. If some paper got rejected, it's likely that it's not an "awesome" paper

**Comment by xiabingquan** [comment]
Ref: https://openreview.net/forum?id=rJFOptp6Z.

**Comment by dkozlov** [comment]
@xiabingquan thank you for the help! I removed https://github.com/dkozlov/awesome-knowledge-distillation/commit/dc63bdfc4fbf9f823f35a2f15efc48fa3e6f0b4b from the list. 

> Some papers are far away from "awesome". 

Could you please share links to papers that you think are far from "awesome"?

> I hope that the owner of this repo could be more strict with the quality of the listed papers, and append more information about the publication status of the papers. If some paper got rejected, it's likely that it's not an "awesome" paper

Sure, I will improve the curation of https://github.com/dkozlov/awesome-knowledge-distillation repository.

Feel free to add a MR to this repository if you find any quality issue.

**Comment by dkozlov** [comment]
@xiabingquan can we close this issue?
